pub mod helloworld {
    // This macro includes the code generated by build.rs
    tonic::include_proto!("helloworld");
}

use domain::{Message, MessageRequest};
use helloworld::{HelloReply, HelloRequest};

impl From<MessageRequest> for HelloRequest {
    fn from(req: MessageRequest) -> Self {
        HelloRequest { name: req.name }
    }
}

impl From<HelloRequest> for MessageRequest {
    fn from(req: HelloRequest) -> Self {
        MessageRequest { name: req.name }
    }
}

impl From<HelloReply> for Message {
    fn from(reply: HelloReply) -> Self {
        Message {
            text: reply.message,
        }
    }
}

impl From<Message> for HelloReply {
    fn from(msg: Message) -> Self {
        HelloReply { message: msg.text }
    }
}
